### ISSUE TITLE
"puppet module install shoekstra/puppet-owncloud" only installs version 0.1.1

### ISSUE THREAD

**Issue by Timokasse** [shoekstra/puppet-owncloud#18]
Hello,

I am trying to use shoekstra/puppet-owncloud on a Ubuntu 14.04 LTS 64b with the usual command `puppet module install shoekstra/puppet-owncloud`. But it only installs version 0.1.1 when, at the time of writing this issue, the latest stable version is 0.4.1.

The version of puppet I use is 3.8.2.

On another server, with same Ubuntu 14.04.3 LTS, I get version 0.4.0 of owncloud module. It's a much more recent version but still not the latest.

Why is that so?

Thank,
Timok

**Comment by shoekstra** [comment]
Hi Timok,

I'm not sure why you are having these hassles, perhaps it's something to pick up with Puppetlabs?  It isn't a module issue but rather an issue with installing a module so they would be best placed to assist you.

Sorry I'm not able to help further.

**Comment by jmnavarrol** [comment]
> I'm not sure why you are having these hassles, perhaps it's something to pick up with Puppetlabs?

See #19: probably older dependencies on metadata.json.
