### ISSUE TITLE
Publish current code to the Puppet Forge

### ISSUE THREAD

**Issue by jmnavarrol** [shoekstra/puppet-owncloud#23]
As told in #19, preferred method to install a puppet module is through the Puppet Forge.  Current version at the Forge is 0.4.1 from Jul 19th 2015 which suffers from known bugs.

Please publish your most current stable version to the Forge.

**Comment by shoekstra** [comment]
0.4.2 has been released to the Forge.

**Comment by jmnavarrol** [comment]
Thanks a lot!

I still having problems, though.  Since they are more focused with #19 scope, I'll comment them there (basically, I'm stuck with version 0.1.1 of your module).  Please see there and consider reopening that issue.
