### ISSUE TITLE
New repository

### ISSUE THREAD

**Issue by gardouille** [shoekstra/puppet-owncloud#26]
Hi,

Since ~22 december, Owncloud provide a new repository:
https://download.owncloud.org/download/repositories/stable/owncloud/

And only the new one will provide latest update:
http://download.owncloud.org/download/repositories/stable/: 8.2.2-1.1
http://download.opensuse.org/repositories/: 8.1.5

Source: https://owncloud.org/blog/owncloud-8-2-2-8-1-5-8-0-10-and-7-0-12-here-with-sharing-ldap-fixes/

Can you eventually update the module?

Thanks :)

**Comment by shoekstra** [comment]
Very cool!  Yes - will get this implemented in next day or so.

Thanks for the heads up.

**Comment by BeneDicere** [comment]
This would be very interesting for us too.
Right now we disabled the repo management by this module and add it by our own. The next problem will be that owncloud-server is no longer available:

**Comment by project0** [comment]
#32 Update to  debian based repo.
Be carefull, this will update owncloud to version 9 since owncloud-server has been renamed to owncloud!

**Comment by shoekstra** [comment]
This has been fixed in https://github.com/shoekstra/puppet-owncloud/commit/8a5cd78c11a2028b39edbbabc202afe37f02cc4a.

Will release latest version to the forge tomorrow.
