### ISSUE TITLE
Rewrite rule on port 80

### ISSUE THREAD

**Issue by svigneux** [shoekstra/puppet-owncloud#7]
Tiny typo in the apache virtualhost section; 
When one redirects to HTTP to HTTPS, the variable HTTPS_HOST is not defined. 

```
It could be rewritten as below:   
#redirect non-SSL traffic to SSL site
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
```

Anyways, I'm using this class on Debian Jessie and it works great. 
Keep up the good work && many thanks!

**Comment by shoekstra** [comment]
Thanks - and thank you!  Not sure how I missed this one, redirection was working when doing acceptance tests.

I'll fix shortly and update the supported OSes.  Thanks for the update!
