### ISSUE TITLE
This module do not work in Ubuntu Precise 12.04 when manage_repo is true

### ISSUE THREAD

**Issue by guimaluf** [shoekstra/puppet-owncloud#8]
Ubuntu 12.04 does not resolve owncloud dependencies when installing via repository(`manage_repo = true`)

Package `owncloud-server` requires `php5 (5.4.0)` which is unavailable in Ubuntu 12.04.5

```bash
ubuntu1204# apt-cache showpkg php5  
Package: php5
Versions: 
5.3.10-1ubuntu3.17
```

**Comment by shoekstra** [comment]
Hmm, it may be related to ownCloud 8 dependency as ownCloud 7 didn't have this issue on Precise.

Will take a look this evening and get back to you, thanks for the feedback!

**Comment by shoekstra** [comment]
Found the problem - the package depends on another ownCloud package that is not being installed but is available in the repository.  Also found a reliable PPA to use for PHP5.4 so will update the module to use it.  I also want to fix the module to work with the new apt and concat modules, so will push a new release once that has been fixed too.

**Comment by shoekstra** [comment]
Hi,

Bit swamped with work at the moment but hope to clear the backlog of issues over the weekend and push a new release to the forge.

**Comment by shoekstra** [comment]
This has been fixed in the next release to the forge.
