### ISSUE TITLE
Install ownCloud from git source

### ISSUE THREAD

**Issue by guimaluf** [shoekstra/puppet-owncloud#9]
I'm looking forward to make this module supports installation from a git repository. What do you think about it?

My experience and knowledge with the whole puppet development ecosystem(puppet, beaker, rspec, etc.) is very limited, but I wish do learn more and do better.

I've read the contributing guidelines and I'm trying to run `rake spec` and `rake acceptance`.
In a clean clone `rake spec` gives me `89 examples, 72 failures` and I couldn't run `rake acceptance` with docker. Any hint about it?

Thanks in advance!

**Comment by guimaluf** [comment]
I've configured vagrant and could run `rake acceptance`. 
For `rake test` looks like `concat` dependencies wasn't resolved, so I'd to include 
`file_concat: "https://github.com/electrical/puppet-lib-file_concat.git"` in order to get tests running.

**Comment by shoekstra** [comment]
Hi,

Re acceptance tests: I didn't get around to finish the acceptance tests properly for this module so they haven't been checked in.  There's a half complete version that I didn't want to push to GH and don't have any plans to finish them at this time (you're welcome to send a PR, but at the moment I'm just bug fixing and not adding any new features).  I tested the module manually using Vagrant on CentOS, Debian and Ubuntu before saying they were supported.

Re installation from a git repository, I can't imagine why someone would want to do this.  There are official repositories that contain stable releases which will install the dependencies for you.  You would spend too much time trying to work out what was missing when trying to install from git.  

Software should be deployed from packages, not git IMO.  What is the reason you want to do this?  I'm intrigued :)

**Comment by guimaluf** [comment]
Hi @shoekstra, I appreciate your response! Thank you!

Actually the acceptance tests were more a prof of concept then a really acceptance test. I think it doest the job :) I managed to make `rake spec` works, I've pinned `puppetlabs/apt` and `puppetlabs/concat` version and now it's working. 
```
Finished in 1 minute 11.31 seconds
89 examples, 0 failures
```

**Comment by guimaluf** [comment]
I need to install owncloud from git cause my private repository have some modification which are not included on official packages. I agree with you that software should be deployed from packages. Do you thinks it's easier to make a package of my owncloud repository and just change the repo url and package name?

**Comment by shoekstra** [comment]
If you have a private repository already then it would be best to set `manage_repo => false` and make your owncloud class require your repository.

Take a look at (aptly)[http
